# Generated by Django 5.1.5 on 2025-08-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('show_type', models.CharField(choices=[('text', 'Text'), ('shader', 'Shader'), ('p5', 'P5'), ('wasm', 'WASM')], max_length=100)),
                ('payload', models.JSONField()),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
    ]
