# Generated by Django 5.1.5 on 2025-10-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_kv_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='is_preview',
            field=models.BooleanField(default=False),
        ),
    ]
