# Generated by Django 5.0.6 on 2024-07-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_show_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="KV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("value", models.JSONField()),
            ],
        ),
    ]
