# Generated by Django 5.0.6 on 2024-07-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_kv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="show_type",
            field=models.CharField(
                choices=[("text", "Text"), ("shader", "Shader")], max_length=100
            ),
        ),
    ]
