# Generated by Django 5.0.6 on 2024-07-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_show_show_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="show_type",
            field=models.CharField(
                choices=[("text", "Text"), ("shader", "Shader"), ("p5", "P5")],
                max_length=100,
            ),
        ),
    ]
