# Generated by Django 5.0.6 on 2024-06-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "show_type",
                    models.CharField(choices=[("text", "Text")], max_length=100),
                ),
                ("payload", models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name="HitCounterModel",
        ),
    ]
