# Generated by Django 5.0.6 on 2024-06-27 02:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_show_delete_hitcountermodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
